language: python

dist: focal

cache: pip

notifications:
  email: true

matrix:
  include:
    - python: 3.8
    - python: 3.9
    - python: 3.10
    - python: 3.11

before_install:
- npm install -g npm@latest || npm install -g npm@9
- sudo apt-get update
- sudo apt-get install pandoc
- pip install pypandoc

install:
- pip install tox-travis 'tox<4'

script: tox

before_deploy:
- pip install bump2version
- nvm install --lts
- npm install @semantic-release/changelog
- npm install @semantic-release/exec
- npm install @semantic-release/git
- npm install @semantic-release/github

deploy:
- provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    python: '3.8'
    branch: master

- provider: pypi
  user: __token__
  password: $PYPI_TOKEN
  edge: true
  skip_cleanup: true
  on:
    python: '3.8'
    tags: true
