language: python

dist: xenial

cache: pip

notifications:
  email: true

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

before_install:
- npm install npm@latest -g
- sudo apt-get update
- sudo apt-get install pandoc
- pip install pypandoc
- '[ "${TRAVIS_PULL_REQUEST}" == "false" ] && openssl aes-256-cbc -K $encrypted_9d748cee9f61_key -iv $encrypted_9d748cee9f61_iv -in vpc.env.enc -out vpc.env -d || true'

install:
- pip install tox-travis

script: tox

before_deploy:
- pip install bump2version
- nvm install 12
- npm install @semantic-release/changelog
- npm install @semantic-release/exec
- npm install @semantic-release/git
- npm install @semantic-release/github

deploy:
- provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    python: '3.6'
    branch: master

- provider: pypi
  user: __token__
  password:
    secure: "WeLxaFsQzpJbl2f7O4cmd1wFzaCSO8kLkzQ/FUo2PJ77QYiOPdPDomV1hImfsIIHaEQyOfBtrfj28ZhaNW1fr1GdxfCXaoAUrdrc3/v7K9Fy4GXwoVDKLLf44xon/Cul8s+8dJbkzJJM+qboNqSrocSw6t1vEfl/sZb69+pW+e7cdEvG5dTZRYJexIO8u5N+cxRrlWHfpFcD9bWo9FUuDwHe+5noYcSa5sW3WH3fMjbSeaVEbHAnt4RBc9H/zHMAqE4mXPldb/ukF9uz+Krg91+A9yYRCMGodogRptd74AMQYfQCmpZG/kEKtNUx32ejmMUnAu0ZFesGu+YDLTOJUGpVpF4So3w+ppcIqtfGqyLFiUKlkdbfgx6Av4ZhFfypWTWfhQl/SAbxpSjM/CkmLUxK/doUzT/G/j763ZmheDhFL/vVmGFF7JNTZxCl7J/WiMgeQ03fUvCZ6RmJcuv+zQUWbKgJi/Syplga2DTz6wAi5Lg3jq36FkY+gFko6bCEPmGvxOfbxhLaQ4x0tOcC57sot2wKmKe1DhPUNrVHuru3RNvBRYQ8vy/YJzDx7zoIrMWe3jiXayi1lDogkP1J6PMyGWwWfFzVx7yGeFWetRPBziWvQh9+e3eRtPdbxkMssNH5wt/p/ntp119dhjZIIwJ96/QOglpzdqvU+Pn30N0="
  repository: https://upload.pypi.org/legacy
  skip_cleanup: true
  on:
    python: '3.5'
    tags: true